name: Deploy to gh-pages

on:
  push:
    branches: [master, pages-deploy]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: "^20"

      - name: npm install
        env:
          CI: true
        run: |
          npm run clean
          npm i

      - name: Build
        env:
          ENV: "production"
        run: |
          export NODE_OPTIONS=--max_old_space_size=8192
          npm run build
          cp build/client/index.html build/client/404.html
          ls -al build/client

      - name: GitHub Pages Deploy Action
        uses: JamesIves/github-pages-deploy-action@v4
        with: # optional
          folder: "build/client"
