name: Deploy to gh-pages

on:
  pull_request:
    branches: []
  push:
    branches: [web-eth]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: "^20"

      - name: npm install
        env:
          CI: true
        run: |
          npm run clean
          npm i

      - name: Build
        env:
          ENV: "production"
        run: |
          export NODE_OPTIONS=--max_old_space_size=8192
          npm run build
          cp build/client/index.html build/client/404.html
          ls -al build/client

      - name: Simple deploy with git
        uses: rdarida/simple-github-pages-deploy-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GHB_DEFAULT_TOKEN }}
        with: # optional
          git-base-folder: "build/client"
